version: '3'

tasks:
  lint:
    cmds:
      - cd backend && uv run ruff check --fix --select I

  test:
    cmds:
      - ./.venv/bin/pytest ./tests -vv

  add-migration:
    cmds:
      - cd backend && uv run alembic revision --autogenerate -m "{{.CLI_ARGS}}"

  migrate:
    cmds:
      - cd backend && uv run alembic upgrade head

  run:
    cmds:
      - cd backend && uv run manage.py run

  publish:
    cmds:
      - git add .
      - git commit -m "{{.CLI_ARGS}}"
      - git push origin $(git branch --show-current)
