"""add-validations-columns

Revision ID: 95ae18a32737
Revises: 1e3f792b40a9
Create Date: 2025-12-14 12:52:11.898170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "95ae18a32737"
down_revision: Union[str, Sequence[str], None] = "1e3f792b40a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("validations", sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("validations", sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("validations", "icon")
    op.drop_column("validations", "label")
    # ### end Alembic commands ###
