"""'init db'

Revision ID: e83562c1f726
Revises:
Create Date: 2025-12-13 14:50:06.497732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e83562c1f726"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("disabled", sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_table("validations",
    sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("rules",
    sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("validation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(["validation_id"], ["validations.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_rules_validation_id"), "rules", ["validation_id"], unique=False)
    op.create_table("tokens",
    sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("token_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_tokens_access_token"), "tokens", ["access_token"], unique=False)
    op.create_index(op.f("ix_tokens_user_id"), "tokens", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokens_user_id"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_access_token"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_index(op.f("ix_rules_validation_id"), table_name="rules")
    op.drop_table("rules")
    op.drop_table("validations")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
